Disallow running as root
Resolves #11

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -23,6 +23,12 @@ function assert_not_at_home()
     esac
 }
 
+function assert_not_root()
+{
+    [[ $EUID -ne 0 ]] || {
+        echo "ERROR: Do not run as root"; exit 1; }
+}
+
 function source_library()
 {
     for file in $LIBRARY_DIR/*.sh
@@ -62,6 +68,7 @@ function run_modules()
 function main()
 {
     check_has_bash4
+    assert_not_root
     assert_not_at_home
     source_library
     run_modules "$@"
